### ISSUE TITLE
Replace default text

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-chapter-bristol-uk#3]
The default text is shown, it needs to be replaced with Bristol UK chapter specific text

**Comment by craigfrancis** [comment]
Good point, do you have any ideas on what it should say?

Some UK examples:

- [London](https://owasp.org/www-chapter-london/)
- [Birmingham](https://owasp.org/www-chapter-birmingham-uk/)
- [Newcastle](https://owasp.org/www-chapter-newcastle-uk/)
- [Scotland](https://owasp.org/www-chapter-scotland/)

Main elements:

- Call For Speakers (I assume this should be directed to Katy?)
- Code of Conduct.
- Next Meeting/Event (shall we simply link to [Meetup.com/OWASP-Bristol](https://www.meetup.com/OWASP-Bristol/)?)
- When we meet.
- Sponsors.

I can imagine this would be a page I would forget to update, so maybe keep it simple?

---

**Welcome to the OWASP Bristol (UK) Chapter**

We meet five times a year, usually on a Thursday, as advertised on [Meetup.com/OWASP-Bristol](https://www.meetup.com/OWASP-Bristol/).

If you would like to give a talk, please review the [OWASP Speaker Agreement](https://wiki.owasp.org/index.php/Speaker_Agreement) and send your talk title, abstract and speaker bio to [Katy Anton](mailto:katy.anton@owasp.org).

**Code of Conduct**

We hope you enjoy our events, we care deeply about inclusivity and diversity so that OWASP is a comfortable and welcoming community for everyone. Please reach out to one of our chapter leaders if you have any feedback or would like to speak to us, we take these matters very seriously. You can find out more about our policies here: <https://owasp.org/www-policy/operational/code-of-conduct.html>

---

As to why "five times a year":

- 2020 x 2, so far
- 2019 x 5
- 2018 x 5
- 2017 x 6
- 2016 x 6
- 2015 x 1

As to why "on a Thursday", but could also be the "3rd Thursday of the month":

- Wed 2nd x 1
- Thu 1st x 1
- Thu 2nd x 4
- Thu 3rd x **12**
- Thu 4th x 5
- Thu 5th x 1
- Fri 3rd x 1

Based on the last 23 meetings, plus the next 2 planned:

- 2020-03-19 - 3rd Thu Mar
- 2020-02-27 - 4th Thu Feb
- 2019-11-14 - 2nd Thu Nov
- 2019-09-12 - 2nd Thu Sep
- 2019-07-18 - 3rd Thu Jul
- 2019-06-06 - 1st Thu Jun
- 2019-01-09 - 2nd Wed Jan
- 2018-11-15 - 3rd Thu Nov
- 2018-09-27 - 4th Thu Sep
- 2018-06-14 - 2nd Thu Jun
- 2018-04-19 - 3rd Thu Apr
- 2018-02-15 - 3rd Thu Feb
- 2017-11-30 - 5th Thu Nov
- 2017-11-23 - 4th Thu Nov
- 2017-09-28 - 4th Thu Sep
- 2017-06-22 - 4th Thu Jun
- 2017-04-20 - 3rd Thu Apr
- 2017-03-09 - 2nd Thu Mar
- 2016-11-17 - 3rd Thu Nov
- 2016-09-15 - 3rd Thu Sep
- 2016-07-21 - 3rd Thu Jul
- 2016-05-20 - 3rd Fri May
- 2016-03-17 - 3rd Thu Mar
- 2016-01-21 - 3rd Thu Jan
- 2015-11-19 - 3rd Thu Nov

---

    $('.list--infinite-scroll.eventList-list').querySelectorAll('time').forEach(function(e) {var d = new Date(e.getAttribute('datetime') * 1); console.log(d.toISOString(), d, d.getWeekOfMonth())});

**Comment by katyanton** [comment]
migrated old content to github
